### ISSUE TITLE
a better scroll bar

### ISSUE THREAD

**Issue by super-lurker** [TheKersalMassive/ReskinPS5#18]
make the scroll bar the same color ,transparency and the same margins as the top UI

**Comment by TheKersalMassive** [comment]
Added transparency and color to match the top preset filter styling.
Margins are tough to achieve as it depends on the size of the artwork as well as horizontal/vertical layout as well as number of rows/columns, so leaving it as default

**Comment by TheKersalMassive** [comment]
Added to v1.3
