### ISSUE TITLE
last items not showing correctly

### ISSUE THREAD

**Issue by super-lurker** [TheKersalMassive/ReskinPS5#19]
issue: last items not showing correctly
![sshot-2021-11-15-15-48-58](https://user-images.githubusercontent.com/13076066/141742898-4fd9bb47-7e70-44bb-b602-05ddb2518666.png)
![sshot-2021-11-15-15-49-13](https://user-images.githubusercontent.com/13076066/141742917-64bbd4ae-198f-4d77-8c60-ecb2061cd093.png)
![sshot-2021-11-15-15-49-23](https://user-images.githubusercontent.com/13076066/141742918-27da27b1-346c-497d-ab6c-2758192a8603.png)

how to replicate:
![sshot-2021-11-07-21-24-23](https://user-images.githubusercontent.com/13076066/141742973-471bf322-7fe1-4fad-9790-ea816919f025.png)
![sshot-2021-11-15-15-50-03](https://user-images.githubusercontent.com/13076066/141742978-63babe2a-0f55-4264-ae1f-1241a2cbcdbf.png)

**Comment by TheKersalMassive** [comment]
Sorry for the late response, been busy with other things, my findings:

I have sucessfully re-created the bug using your settings, and found that it is an issue with the default theme and not just the reskin theme, as per the below:

![image](https://user-images.githubusercontent.com/90322803/145731190-f58a3956-4db1-4a7e-b7c6-0290153f0381.png)

Can you check on the default theme and if it happens there, you may need to raise an issue with Crow
