### ISSUE TITLE
XBOX Classic filter not showing in bar

### ISSUE THREAD

**Issue by Pixxel123** [TheKersalMassive/ReskinPS5#20]
I've set and saved a filter as `XBOX Classic`, according to the instructions, but no logo appears.

![image](https://user-images.githubusercontent.com/36304206/142511349-4f974483-b6e6-4699-97a8-056f937fd9da.png)

As you can see, it is set, but not showing up:

![image](https://user-images.githubusercontent.com/36304206/142511498-820a90ea-d675-4d78-b591-d12273cf9db4.png)

**Comment by TheKersalMassive** [comment]
I have checked the files and 'XBOX Classic' is the correct preset name.

Can you go up and scroll the right of your filters at the top? Past Recently Played?

**Comment by Pixxel123** [comment]
This was it! Filter was there, just hidden. I've renamed Recently Played to have a zero-width space in front and removed Most Played to make more space so that XBOX Classic shows 😄
