### ISSUE TITLE
Shoulder buttons to scroll filters

### ISSUE THREAD

**Issue by Bobby-Analogue** [TheKersalMassive/ReskinPS5#21]
I am loving PS5 reskin. Definitely the sleekest design of all the Playnite skins. So thank you for your work.

It would be super cool, if possible, to use the shoulder buttons to jump between the automatic filters at the top, rather than having to navigate to the next one and click. 

Not sure if that's possible or not. But if it is, please please please can you do it?? Pretty please?

**Comment by TheKersalMassive** [comment]
The theme already supports scrolling the preset filters via the:
- LB and RB shoulder buttons on a XBOX controller.
- F2/F3 on keyboard

This is the same as the default skin.

What controller are you using?
