### ISSUE TITLE
Can't edit order of Filtered Categories

### ISSUE THREAD

**Issue by DaMushroomCloud** [TheKersalMassive/ReskinPS5#23]
The order of which game systems or launchers that appear at the top are in alphabetical order. It would be nice if we could edit the order of these categories to make it easier to navigate.

**Comment by TheKersalMassive** [comment]
This is not a theme issue but just the way Playnite currently displays the order of the filter presets.
Nothing I can do until custom sorting is implemented into Playnite.

The current workaround is to add a number prefix to your filters, such as... 1. PS3 2. Nintendo Switch, 3. Genesis
