### ISSUE TITLE
Change custom values on ReskinPS5

### ISSUE THREAD

**Issue by anwar-alsilwy** [TheKersalMassive/ReskinPS5#25]
Hi,
First of all this is not issue.
I like ReskinPS5 theme so much, thanks a lot,
But I need to change somethings: 

1- How can I make the border more thicker, what the value should I change ( using Notepad++);
![border](https://user-images.githubusercontent.com/71539261/149150943-7bd61bf6-3d42-4f15-b71a-49339f053daf.jpg)

2- How can I make background more brightness and clear the dim on background;
![background](https://user-images.githubusercontent.com/71539261/149151236-a4dcdbe5-fdf7-4103-a3e9-46b9fe0477e3.jpg)

**Comment by TheKersalMassive** [comment]
1. Change the **BorderThickness** value under in the **ListGameItemStyle.xaml** file under **DerivedStyles** folder:

`<Border x:Name="MainBorder" Opacity="0" BorderThickness="3" CornerRadius="3" Style="{DynamicResource AnimatedCoverBrush}" Tag="False" Visibility="Collapsed" >`

2. Delete the below code in **GameDetails.xaml** under the **Views** folder:

```
                        <Border Background="{DynamicResource GameDetailsOverlay}" Grid.Row="0" Grid.Column="0" Grid.ColumnSpan="3" Grid.RowSpan="3" >
						 <Border.Style>
                                <Style TargetType="Border">
                                    <Style.Triggers>
                                        <DataTrigger Binding="{Binding DisplayBackgroundImage}" Value="{x:Null}">
                                            <Setter Property="Visibility" Value="Collapsed" />
                                        </DataTrigger>
                                    </Style.Triggers>
                                </Style>
                            </Border.Style>
                        </Border>
```

Please note you will need to repeat these steps every time the theme is updated

**Comment by anwar-alsilwy** [comment]
WOW !!!
Thank you so much for that.
I will test it tomorrow.

**Comment by anwar-alsilwy** [comment]
WOW !!!
Thank you so much for that.
I will test it tomorrow.
