### ISSUE TITLE
Suggestion: New Icon/Platform logo (Master System)

### ISSUE THREAD

**Issue by roe617** [TheKersalMassive/ReskinPS5#26]
Really loving the theme.  Many thanks for this.

Was just wondering if you could possibly add a logo for the Sega Master System in the same style as the ones that are already here.

Thanks

**Comment by TheKersalMassive** [comment]
Added to v1.6 update as **_Sega Master System_**

![image](https://user-images.githubusercontent.com/90322803/156665322-90f8f01b-e62b-42a3-8fe1-732b491c3578.png)
