### ISSUE TITLE
New Icon - Nvidia

### ISSUE THREAD

**Issue by lennysdead** [TheKersalMassive/ReskinPS5#29]
Icon for Nvidia Gamestream / Moonlight

**Comment by lennysdead** [comment]
![Nvidia](https://user-images.githubusercontent.com/31143730/154952792-45a8ff20-ddf8-4542-85da-24a04e9d8311.png)

**Comment by lennysdead** [comment]
![Moonlight](https://user-images.githubusercontent.com/31143730/154953095-e5dd1258-c9ce-442c-be6f-df2545e76f17.png)
this one needs inverting though sorry

**Comment by TheKersalMassive** [comment]
Added both logos to next update v1.6 as **_Moonlight_** & _**Nvidia Gamestream**_

![image](https://user-images.githubusercontent.com/90322803/156723141-3868fbdd-f1d4-45d0-ac0d-8d4eaa3310bf.png)
