### ISSUE TITLE
Request: Add MAME Icon

### ISSUE THREAD

**Issue by ch3vr0n5** [TheKersalMassive/ReskinPS5#32]
This is a request to add the attached MAME png to the icon collection (\Icons\Filters)

![MAME](https://user-images.githubusercontent.com/987282/163259400-e56bd53a-cb54-44ca-895c-e1a24b1c7cf9.png)

![example](https://user-images.githubusercontent.com/987282/163260277-c6c7cb43-3256-4271-a8fd-3bfc0a887838.png)

**Comment by TheKersalMassive** [comment]
Will add in next update (no ETA)

**Comment by TheKersalMassive** [comment]
Added in next release
