### ISSUE TITLE
Request: Sega Saturn icon

### ISSUE THREAD

**Issue by ds22x** [TheKersalMassive/ReskinPS5#34]
Icon for Sega Saturn.

**Comment by ds22x** [comment]
![Sega Saturn](https://user-images.githubusercontent.com/45218067/164997826-cb7c3451-2992-46e9-aedb-6b0f82c45a23.png)

**Comment by TheKersalMassive** [comment]
Will add in next update (no ETA)

**Comment by TheKersalMassive** [comment]
Added to next release
