### ISSUE TITLE
Cycling through preset filters using LB/RB issue

### ISSUE THREAD

**Issue by stanejera** [TheKersalMassive/ReskinPS5#37]
Hi, first off, I super love your theme and all the effort you put into it! 

But I have this one issue where when I'm cycling through the preset filters using the LB/RB shortcuts, the top icons do not "scroll through" when reaching the end of the visible list. I have a relatively long list so not all icons are shown at the top. The listed games in the main frame do change but you don't know which filters are applied since the highlighted icons at the top are no longer visible. 

Scrolling on the top icons/filters with D-Pad/LS + A  works as intended but LB/RB just feels more intuitive and faster.

Hope my explanation makes sense but I've attached a GIF just in case. I'm not sure if this is a bug on my end or an overall playnite limitation.

Again, thank you for your work on this theme!
![github3](https://user-images.githubusercontent.com/108636612/177062925-e0e2b0af-67bf-4869-9b94-e01a10c1d329.gif)
!

**Comment by TheKersalMassive** [comment]
Hey, thanks for the GIF demo which helps a lot.

I have tested this and it seems this is not a theme issue but a general Playnite issue. 

If you re-test with the **default** playnite theme and try to add more preset filters and then navigate through LB/RB, then they also do not come into focus when using the shoulder buttons.

My suggestion is to raise this issue on the main Playnite github. Thanks

**Comment by stanejera** [comment]
Thanks for the reply @TheKersalMassive! Copy, will make a suggestion the playnite github.
