### ISSUE TITLE
Icons up top and platform labes not working

### ISSUE THREAD

**Issue by IonasPolitis** [TheKersalMassive/ReskinPS5#41]
I updated from the app/skin directly to version 1.7 and they just don't work. When you turn on fullscreen mode the first game that you are hovering overing on does display the platform label (on the game cover art), but from the momment you switch to a diffrent category filter, it disapears like all the others. Icons for category filters up top (Switch, WiiU, PS4, etc.) straight up don't work.

Hope you get the time to patch it if it's not only a me issue, because this skin is actually really beautiful and great. If it's just me...well...please help xD

**Comment by TheKersalMassive** [comment]
Will be fixed in the next few days, after the next Playnite update (assuming 10.3) which should fix the image loading that causes lag and disapears.

In the meantime, I'll update to 1.8 to fix the laginess but remove the filter icons and labels so it doesn't lag

**Comment by TheKersalMassive** [comment]
All should work now when you update to Playnite v10.3
