### ISSUE TITLE
Quest VR filter icon

### ISSUE THREAD

**Issue by rakinishraq** [TheKersalMassive/ReskinPS5#42]
I made a quick platform filter icon for Quest games.

![Quest](https://user-images.githubusercontent.com/47909358/196811687-49683ff3-a207-4377-b0f1-69bf14a54934.png)

**Comment by TheKersalMassive** [comment]
Thanks, will add to next release

**Comment by TheKersalMassive** [comment]
Added as 'Quest VR' in v1.11
