### ISSUE TITLE
Platform Image Labels won't show up

### ISSUE THREAD

**Issue by RealSalemTheCat** [TheKersalMassive/ReskinPS5#43]
Hey!

I can't figure out why the platform image label won't appear as shown in the Theme Screenshots.

Here, it only show the platform name text inside a box.

Tried to rename labels image file names to match platform names in Playnite, but it doesn't seem to work at all.  What am I missing?

Thanks in advance.

**Comment by TheKersalMassive** [comment]
Hey
If you're referring to the platform labels that were in a previous version, then they no longer work until I've reworked the platform id code to it.

It should be in the next release though :)

![image](https://raw.githubusercontent.com/TheKersalMassive/ReskinPS5/main/Media/labels_01.jpg)

**Comment by RealSalemTheCat** [comment]
Yeah, precisely! That's what I was talking about. I thought I was doing something wrong, haha. I'll keep an eye on updates.

They're not implemented in Reskin XBOX, right? All I see is Source labels on game covers.

Anyways, thanks for the reply and good work! You rock! 😁

**Comment by TheKersalMassive** [comment]
Added to v1.11
